In [4]:
import pandas as pd
df = pd.read_csv("Automobile_data.csv")
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [5]:
#body-style column의 key를 기준으로 그룹핑
df.groupby('body-style').groups.keys()

dict_keys(['convertible', 'hardtop', 'hatchback', 'sedan', 'wagon'])

In [6]:
# body-style -> 'convertible' key로 그룹된 값들 출력
style = df.groupby('body-style')
style.get_group("convertible")

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
72,3,142,mercedes-benz,gas,std,two,convertible,rwd,front,96.6,...,234,mpfi,3.46,3.1,8.3,155,4750,16,18,35056
128,3,?,porsche,gas,std,two,convertible,rwd,rear,89.5,...,194,mpfi,3.74,2.9,9.5,207,5900,17,25,37028
172,2,134,toyota,gas,std,two,convertible,rwd,front,98.4,...,146,mpfi,3.62,3.5,9.3,116,4800,24,30,17669
189,3,?,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.4,8.5,90,5500,24,29,11595

In [7]:
#body-style, drive_wheels column의 key를 중심으로 그룹핑
double_grouping = df.groupby(["body-style","drive-wheels"])
double_grouping.first()

                          symboling normalized-losses           make  \
body-style  drive-wheels
convertible fwd                   3                 ?     volkswagen
            rwd                   3                 ?    alfa-romero
hardtop     fwd                   2               168         nissan
            rwd                   0                93  mercedes-benz
hatchback   4wd                   0                 ?           audi
            fwd                   2               121      chevrolet
            rwd                   1                 ?    alfa-romero
sedan       4wd                   2               164           audi
            fwd                   2               164           audi
            rwd                   2               192            bmw
wagon       4wd                   0                85         subaru
            fwd                   1                 ?           audi
            rwd                  -1                93  mercedes-benz

                         fuel-type aspiration num-of-doors engine-location  \
body-style  drive-wheels
convertible fwd                gas        std          two           front
            rwd                gas        std          two           front
hardtop     fwd                gas        std          two           front
            rwd             diesel      turbo          two           front
hatchback   4wd                gas      turbo          two           front
            fwd                gas        std          two           front
            rwd                gas        std          two           front
sedan       4wd                gas        std         four           front
            fwd                gas        std         four           front
            rwd                gas        std          two           front
wagon       4wd                gas        std         four           front
            fwd                gas        std         four           front
            rwd             diesel      turbo         four           front

                          wheel-base  length  width  ...  engine-size  \
body-style  drive-wheels                             ...
convertible fwd                 94.5   159.3   64.2  ...          109
            rwd                 88.6   168.8   64.1  ...          130
hardtop     fwd                 95.1   162.4   63.8  ...           97
            rwd                106.7   187.5   70.3  ...          183
hatchback   4wd                 99.5   178.2   67.9  ...          131
            fwd                 88.4   141.1   60.3  ...           61
            rwd                 94.5   171.2   65.5  ...          152
sedan       4wd                 99.4   176.6   66.4  ...          136
            fwd                 99.8   176.6   66.2  ...          109
            rwd                101.2   176.8   64.8  ...          108
wagon       4wd                 96.9   173.6   65.4  ...          108
            fwd                105.8   192.7   71.4  ...          136
            rwd                110.0   190.9   70.3  ...          183

                          fuel-system  bore stroke  compression-ratio  \
body-style  drive-wheels
convertible fwd                  mpfi  3.19    3.4                8.5
            rwd                  mpfi  3.47   2.68                9.0
hardtop     fwd                  2bbl  3.15   3.29                9.4
            rwd                   idi  3.58   3.64               21.5
hatchback   4wd                  mpfi  3.13    3.4                7.0
            fwd                  2bbl  2.91   3.03                9.5
            rwd                  mpfi  2.68   3.47                9.0
sedan       4wd                  mpfi  3.19    3.4                8.0
            fwd                  mpfi  3.19    3.4               10.0
            rwd                  mpfi   3.5    2.8                8.8
wagon       4wd                  2bbl  3.62   2.64                9.0
            fwd                  mpfi  3.19    3.4                8.5
            rwd                   idi  3.58   3.64               21.5

                         horsepower peak-rpm city-mpg  highway-mpg  price
body-style  drive-wheels
convertible fwd                  90     5500       24           29  11595
            rwd                 111     5000       21           27  13495
hardtop     fwd                  69     5200       31           37   8249
            rwd                 123     4350       22           25  28176
hatchback   4wd                 160     5500       16           22      ?
            fwd                  48     5100       47           53   5151
            rwd                 154     5000       19           26  16500
sedan       4wd                 115     5500       18           22  17450
            fwd                 102     5500       24           30  13950
            rwd                 101     5800       23           29  16430
wagon       4wd                  82     4800       23           29   8013
            fwd                 110     5500       19           25  18920
            rwd                 123     4350       22           25  28248

[13 rows x 24 columns]

In [8]:
# dobule_grouping된 데이터 중, normalized-losses column의 최소값
style['normalized-losses'].max()

body-style
convertible    ?
hardtop        ?
hatchback      ?
sedan          ?
wagon          ?
Name: normalized-losses, dtype: object

In [9]:
# dobule_grouping된 데이터 중, normalized-losses column의 최소값
style['normalized-losses'].min()

body-style
convertible    134
hardtop        134
hatchback      101
sedan          102
wagon          103
Name: normalized-losses, dtype: object

In [10]:
# body-stype의 key를 기준으로 평균값
style.mean()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
body-style,,,,,,,,,,
convertible,2.833333,92.700000,170.383333,65.583333,51.433333,2801.666667,157.166667,8.933333,20.500000,26.000000
hardtop,1.875000,98.500000,176.937500,66.612500,52.850000,2810.625000,176.250000,10.725000,21.625000,27.250000
hatchback,1.585714,95.535714,166.592857,65.247143,52.108571,2348.185714,114.400000,9.027429,26.314286,32.171429
sedan,0.333333,100.619792,177.585417,66.260417,54.337500,2610.593750,130.822917,10.937500,25.322917,30.833333
wagon,-0.160000,102.156000,181.304000,66.256000,56.728000,2784.240000,123.840000,10.316000,24.040000,28.720000

In [11]:
# 특정 key에 대한 평균값
style.get_group("convertible").mean()

symboling            2.833333e+00
wheel-base           9.270000e+01
length               1.703833e+02
width                6.558333e+01
height               5.143333e+01
curb-weight          2.801667e+03
engine-size          1.571667e+02
compression-ratio    8.933333e+00
horsepower           1.851853e+15
peak-rpm             8.334167e+22
city-mpg             2.050000e+01
highway-mpg          2.600000e+01
price                2.249194e+28
dtype: float64

In [12]:
# body-style column의 key로 기준으로, symboling 데이터에 대한 count
style['symboling'].count()

body-style
convertible     6
hardtop         8
hatchback      70
sedan          96
wagon          25
Name: symboling, dtype: int64